### ISSUE TITLE
Try build Warehouse to flatpak

### ISSUE THREAD

**Issue by NobeliY** [flattool/warehouse#158]
- [+] I have read the `README.md` document
-  [+] I am using the latest version of Warehouse
- [ ] I am using the Flatpak package of Warehouse
- [+] I have not found any other opened issues on the same topic

## Describe the issue in detail
We are trying to assemble in a warehouse and only then we collect, only then we receive: 

> Traceback (most recent call last):
  File "/app/bin/tnappstore", line 46, in <module>
    from TnAppStore import main
  File "/app/share/tnappstore/TnAppStore/main.py", line 27, in <module>
    gi.require_version("Flatpak", "1.0")
  File "/usr/lib/python3.12/site-packages/gi/__init__.py", line 122, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Flatpak not available

**Comment by heliguy4599** [comment]
I've had this happen to me before. I've gotten around it by using `flatpak-builder` from Flathub: `org.flatpak.Builder`. I've found distro packages of flatpak-builder dislike the libflatpak stuff in Warehouse
